### ISSUE TITLE
Ability to handle messy data by learning optimal NaN imputation and outlier removal

### ISSUE THREAD

**Issue by franz101** [winedarksea/AutoTS#14]
Currently I can see only a handful features for imputation in tools.
What is the status here? Any plans to implement Kaiman filtering for example?

**Comment by winedarksea** [comment]
Simple = fast, something important with hundreds of models being run.
I did recently add support for the scikit-learn IterativeImputer which can be used for more advanced NaN handling.
I have no plans to add the Kalman filter since that is already handled by statsmodels, and is used by some of the statsmodel models.
