### ISSUE TITLE
Question: how to use logistic growth with FBProphet model?

### ISSUE THREAD

**Issue by jwpestrak** [winedarksea/AutoTS#156]
It is not obvious (at least to me), how to use `logistic` growth with the `FBProphet` model.  I have generated useful forecasts using `logistic` growth by running `FBProphet` outside of the `AutoTS` framework, but would like to take advantage of the genetic algorithm-based hyperparameter tuning, preprocessing, and other utilities offered by `AutoTS`.

I am using version 0.5.3 of `AutoTS`, and after grepping `AutoTS/autots/` for the fixed string "logistic", there are only three matching lines in files underneath this directory.  None of them are in the file `AutoTS/autots/models/prophet.py`.  

Where can I pass `cap` (and `floor`) values that will be persisted throughout training and prediction?

A code example demonstrating where and how to pass `cap` (and `floor`) values to both the training and the `future` dataframes would be useful. 

I have tried to make changes in the following files (but am unable to complete training-and-prediction  job without an exception being raised):
* `AutoTS/autots/models/prophet.py` [add "logistic" as a `growth` option],
* `AutoTS/autots/evaluator/auto_ts.py` [create `cap` and `floor` series in the `df_wide_numeric` dataframe].

**Comment by winedarksea** [comment]
As I think you've noticed, I was never expecting anyone to use the logistic option as it required specifying a cap and a floor. The problem is, I don't want to add a cap and floor option to the upper level model options when it only applies to one model. Furthermore, even if you did add a cap and floor, using an preprocessing transformers would result in that cap and floor not being applied correctly as the transfomers may shift it out of that range. 

I personally think this is handled by the higher level `constraint` option, not sure if you have tried that. It allows specifying constraint a number of different ways, including both a soft or hard cap on the values of the forecast which accomplishes much the same thing. Would that work for you?

I am willing to make changes to try to make something work, but currently am inclined to stick with the current constraint.

**Comment by jwpestrak** [comment]
Thanks for the reply.  I appreciate the decision not encourage the use of the logistic option as it only applies to the Prophet model.  I will try using the `constraint` option instead.
