### ISSUE TITLE
When would be available early stopping option?

### ISSUE THREAD

**Issue by r-matsuzaka** [winedarksea/AutoTS#160]
Hello, again. I found the comment, `It's called 'max' because someday there will be an auto early stopping option, but for now this is just the exact number of generations to run.` at https://github.com/winedarksea/AutoTS/blob/52487e5ea5e3ce0530e1096e239655786227de3f/autots/evaluator/auto_ts.py#L54

Do you plan to implement this feature?

**Comment by winedarksea** [comment]
Not that, but I have something similar released in the latest version `0.5.3` called `generation_timeout` which is the time in minutes that it stops searching for new models, and proceeds instead to validations. I think this fills that need better.

I am not sure if I will add early stopping because I haven't actually seen any value to it. The part that follows, validations, removes overfit models, so there's no need to use early stopping to prevent overfitting like is true for some specific model types.

**Comment by r-matsuzaka** [comment]
Ok, I understood. Thank you very much.
