### ISSUE TITLE
Question: Optimal max_generations

### ISSUE THREAD

**Issue by r-matsuzaka** [winedarksea/AutoTS#161]
I wonder how to set the generation number.  
Is there any optimal number?  

Also, each generation tries only one model randomly?  
Then I should choose more than the number of models available like 40?

**Comment by winedarksea** [comment]
I would usually use at least 10 generations. I have run 1000's. Run as many as you have time to run (generation_timeout you can specify a max search time), because the model search space here is truly massive - millions of potential models. The more generations, the more time you have to search that space. However, many models are 'pretty similar' so you can get close enough with a smaller number of generations.

Number of models per generation depends on number of model types, as well as having an overall max. It is in NewGeneticTemplate parameters. It removes duplicates from those already tried.
    max_results: int = 50,
    max_per_model_class: int = 5,

**Comment by r-matsuzaka** [comment]
> many models are 'pretty similar' so you can get close enough with a smaller number of generations.

Thank you very much.
