### ISSUE TITLE
Trying to push repo

### ISSUE THREAD

**Issue by Killpit** [winedarksea/AutoTS#167]
I am trying to add more financial forecasting examples, but I can't really do it.

**Comment by winedarksea** [comment]
You can't push to a public GitHub repository unless you are an owner of the repo. As a third party user you have to create a pull request (PR). I am also unlikely to approve a pull request for more financial forecasting examples because I don't want to excessively encourage users to get too carried away with investing based on forecasting. Your best bet would probably to publish your examples on a blog such as Medium.
