### ISSUE TITLE
Production mode

### ISSUE THREAD

**Issue by orydatadudes** [winedarksea/AutoTS#17]
assuming i already trained a model and now i went  use it during production.
now let say my data frequently is daily and every day i am getting a new daily data and i need to predict the next day 
how do i add the new daily data to my model without training it from the beginning?
can i use my trained model and giving prediction for every day?
or i have to train my model every time i am getting new daily data and then making predictions for the next day
thanks

**Comment by winedarksea** [comment]
To some extent, you will have to retrain a model every day - that is the nature of time series. 

In the extended_tutorial.md I have an example of how I recommend you put a model 'into production'. That is by saving the template of the best n models. If you only want to save 1 model, you can set n=1. I prefer to set n>1 and then each time it can choose the best model from among several (just in case, as happens like with covid, the environment has changed and some of your models may no longer fit as well).
```
# after fitting an AutoTS model
example_filename = "example_export.csv"  # .csv or .json
model.export_template(example_filename, models='best',
					  n=15, max_per_model_class=3)

# on new training another day
model = AutoTS(forecast_length=forecast_length,
			   frequency='infer', max_generations=0,
			   num_validations=0, verbose=0)
model = model.import_template(example_filename, method='only')  # method='add on'
print("Overwrite template is: {}".format(str(model.initial_template)))
```
One simple approach to reduce compute would also be to increase your forecast_length. Predict a week instead of one day, then only rerun once a week. Or predict weekly level data, then generalize down to the day level.
You could also try ignoring the time component and doing a regular sklearn regression without AutoTS. In my experience, however, most real world forecasting needs to be retrained frequently (I again wave vaguely at covid as just such an example) if it is at all is affected by human behavior and economics.

I would love to hear your feedback on the import and export of templates, whether or not that suits what you are looking for?
