### ISSUE TITLE
Feature Importance

### ISSUE THREAD

**Issue by KajetanPoliak** [winedarksea/AutoTS#172]
I would love to able able to get feature importance when modeling with multiple features.
Is there something like SHAP or LIME? 

I know there is a possibility to get this information in for example Azure ML Studio - AutoML.
Let me know if there is a way to get feature importance. Maybe there is a workaround?

Thank you

**Comment by winedarksea** [comment]
The 'Cassandra' model was specifically designed for providing advanced yet explainable forecasts, so that's probably the model you want to try for understanding feature impact. An example is at the bottom of the cassandra.py file in models.

But in general, never going to happen that feature importance will work for all models because there are so many different types of models here. The statistical models are explainable in a sense, if you look at the details from Statsmodels where available (like VAR).  The traditional ML based models in the ~Regressions could theoretically support SHAP but I haven't bothered integrating it - the model search space includes searching the feature creation space, so given a long enough optimization, it can be assumed the chosen features as seen in the model parameters are all important...
