### ISSUE TITLE
How to know whether the model has picked up external (exogenous) regressors as part of training ? Also, which all features were chosen as part of training ?

### ISSUE THREAD

**Issue by vinitkothari24** [winedarksea/AutoTS#174]
In the best model chosen, How to know whether the model has picked up external (exogenous) regressors as part of training. Also which all features were chosen as per of training ?

**Comment by winedarksea** [comment]
@vinitkothari24 
There are two identical bool flags that can tell you this: `model.regressor_used` and `model.used_regressor_check`

There is a parameter `models_mode` to which you can pass `regressor` to force it to only use regressor models in newly generated models (imported models from a template will still be non-regressor if present).

I've answered questions about feature importances a few times here, and the answer is complicated because it depends on the underlying model being used. You can access information from `VAR` for example, and a few others. And I have an entire model built for the purpose of explainability called `Cassandra` which is worth looking at if you care about features.
