### ISSUE TITLE
Theta Template Eval Error

### ISSUE THREAD

**Issue by emobs** [winedarksea/AutoTS#216]
[AutoTS version 0.6.5]

Not sure if this is a true bug, but on all Theta model templates I get this error: 
Template Eval Error: ValueError('freq T not understood. Please report if you think this is in error.')
The frequency of my input data is 5T and set in the model definition, so not automatically determined by 'infer'.

**Comment by winedarksea** [comment]
Could you print `model.used_frequency` and post that? I made an update to the inferred frequency process and that might be inferring incorrectly?
otherwise could be an issue with the Theta model directly

**Comment by winedarksea** [comment]
That's helpful. Means the bug is specific to the Theta model.
https://www.statsmodels.org/dev/generated/statsmodels.tsa.forecasting.theta.ThetaModel.html

I have confirmed that if I specify `period` specifically (as an int) and not use the auto 'None' for periods it will prevent the issue.

But regardless Theta is too slow at scale. I will for now add period as a not None value if models_mode="deep".
You could also try the model manually with a not None value for period, seeding that in as a template if you want to try running it now
