### ISSUE TITLE
Fitted Values

### ISSUE THREAD

**Issue by AlbertoAlmuinha** [winedarksea/AutoTS#86]
Hi,

I would like to obtain the fitted values of the best model, is this possible?

**Comment by winedarksea** [comment]
@AlbertoAlmuinha 
I assume you mean what might be a called a "backcast" like Prophet does, where you can see what the model looks like forecast across all the past data.

Short answer: No.

I have issues with these... the main reason is that the 'backcast' is always much more accurate than the forecast, because it is predicting on the data it was trained on. And some models simply won't be able to generate a backcast - how do you generate a Last Value Naive for point 0 when there is no history? These are also often generated by one-step ahead forecasts, which exaggerate the effectiveness as well.

If you only need a partial backcast, you can use the `model_forecast` function and pass in the `model.best_model` to it, then pass in a fraction of your training data as df_train. There's an example in the extended tutorial.

That said, happy to consider including this functionality in the future. What exactly do you want this to look like, and for what purpose?

**Comment by AlbertoAlmuinha** [comment]
@winedarksea 

The main purpose is to obtain the model residuals, that are useful in checking whether a model has adequately captured the information in the data. I know that for some models it is not possible to calculate these values but I believe that for most models it is possible and I believe that it can be useful information. Perhaps for models that cannot be obtained, a predefined value or a message could be returned to the user...

I would like to create an R package that connects through `reticulate` with this package and also integrates with the R package `modeltime`...I just need the fitted values to be able to integrate with `modeltime` package.

https://github.com/business-science/modeltime

Regards,

**Comment by winedarksea** [comment]
A true backcast would require a major reworking.

But in a week or two I could probably throw together a backtest that is a bit of hack. It could be a little slow but would deliver backcasts as representative as could be expected for most models.

**Comment by AlbertoAlmuinha** [comment]
That would be awesome, I would appreciate it if you could implement it, I think it would be great!

**Comment by winedarksea** [comment]
@AlbertoAlmuinha 
There is now a `model.back_forecast` function. It is a bit experimental still. 
To get the most accurate representation, `n_splits` should be set to `"auto"` which will run a forecast for each chunk of the data of size `forecast_length`. That tends to be rather slow....
To speed things up, either specify `tail` which only runs on the most recent tail of the data, or change `n_splits` to a small number (like 3) which will run only that many chunks. However, the accuracy of these chunks will not be as representative of the whole. You can also specify `column` to run on only one time series if many are present, although that could be problematic with multivariate models.

**Comment by AlbertoAlmuinha** [comment]
Hi @winedarksea ,

Thank you so much for this! I will give it a try today with your comments in mind.

I'll let you know how it went

Regards
